import { model } from "@medusajs/framework/utils"

/**
 * FaqQuery — stores a customer-submitted support question and the admin answer.
 *
 * Columns
 * ─────────────────────────────────────────────────────────
 *  id              UUID PK (auto-generated by Medusa DML)
 *  customer_name   Display name the customer supplied on the form
 *  customer_email  Email address the customer supplied (stored lowercase)
 *  subject         Short, one-line topic (3-150 chars)
 *  question        Full question text (10-2000 chars)
 *  answer          Admin reply — null until the query is answered
 *  status          "pending" (unanswered) | "answered"
 *  answered_at     Timestamp when admin posted the answer (null if pending)
 *  created_at / updated_at are injected automatically by Medusa
 */
const FaqQuery = model.define("faq_query", {
  id: model.id().primaryKey(),
  customer_name:  model.text(),
  customer_email: model.text(),
  subject:        model.text(),
  question:       model.text(),
  answer:         model.text().nullable(),
  status:         model.enum(["pending", "answered"]).default("pending"),
  answered_at:    model.dateTime().nullable(),
})

export default FaqQuery
